version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_tracker
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./server/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5434:5432"

  dispatcher:
    build: ./dispatcher
    ports:
      - "8080:8080"

  server:
    build: ./server
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/admin


  server-2:
    build: ./server
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/admin

  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8085:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper



volumes:
  postgresql:
  data: {}